### ISSUE TITLE
trace-commons-protocol does not build standalone: a public trait references a feature-gated type

### ISSUE THREAD

**Issue by zmanian** [TraceCommons/trace-commons#486]
`trace-commons-protocol` does not build without an optional feature, so an external consumer cannot depend on it at all.

`cargo build -p trace-commons-protocol` fails on current `main` (`08f4c391`) with no features enabled. This is not a test-only problem -- the library itself does not compile:

```
error[E0433]: cannot find `privacy_filter_near_ai` in `crate`
    --> crates/trace-commons-protocol/src/trace_contribution.rs:2453:43
     |
2453 |         _store: std::sync::Arc<dyn crate::privacy_filter_near_ai::ClassifyWindowStore>,
     |                                    ^^^^^^^^^^^^^^^^^^^^^^ could not find `privacy_filter_near_ai` in the crate root
     |
note: found an item that was configured out
    --> crates/trace-commons-protocol/src/lib.rs:8:9
     |
   7 | #[cfg(feature = "near-ai-privacy-filter")]
   8 | pub mod privacy_filter_near_ai;
```

`cargo check` and `cargo test` fail identically.

## Mechanism

`scoped_to_window_store`, a default method on the public `PrivacyFilterAdapter` trait, takes `Arc<dyn crate::privacy_filter_near_ai::ClassifyWindowStore>` with no `cfg` gate. The module it names is gated behind `near-ai-privacy-filter`, and that feature is not in `[features] default`. So a public trait's signature references a type that does not exist in a default build.

The neighbouring reference at `trace_contribution.rs:2769` is gated correctly (`#[cfg(feature = "near-ai-privacy-filter")]` on `build_near_ai_adapter`), which is what makes this look like an oversight rather than a decision.

Introduced by #481. Confirmed by checking out `origin/main` in a clean worktree and reproducing there, so it is not branch-induced.

## Why CI does not catch it

Every CI job builds the workspace or the server crate, and `trace-commons-server` enables `near-ai-privacy-filter` on the protocol crate. Cargo unifies features across a workspace build, so the module is always present in the configuration CI exercises. Nothing in CI ever builds the protocol crate on its own.

## Why this matters more than a broken test

`CLAUDE.md` states the protocol crate is MIT OR Apache-2.0 specifically because it "ships inside proprietary agent harnesses and must stay permissive". Those consumers depend on it standalone and would not enable a NEAR AI feature. Today such a dependency fails to compile on the first build, before any integration work begins. The permissive licensing is doing no good if the crate cannot be consumed.

## Options

1. Gate the method: put `#[cfg(feature = "near-ai-privacy-filter")]` on `scoped_to_window_store`. Cheapest, but changes the trait's shape by feature, which callers must then also gate.
2. Move `ClassifyWindowStore` out of the gated module into an ungated one. The trait is a storage-shaped abstraction and does not obviously need the NEAR AI adapter's dependencies; only its implementation does.
3. Make the feature non-optional. Contradicts the reason it is optional -- it pulls `reqwest`, `futures`, `tracing`, and `tiktoken-rs` into every consumer.

Option 2 looks right, but the call belongs to whoever shaped the cache in #481.

## Regression guard

Whatever the fix, CI should build the crate on its own so this cannot return:

```
cargo check -p trace-commons-protocol --no-default-features
```

Worth considering for the other permissive crates too, for the same reason: nothing currently proves any of them is consumable outside this workspace.

## Reproduction

```
git checkout main
cargo build -p trace-commons-protocol
```
